default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: hahaha123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 127.0.0.1
  database: erp_system_development

test:
  <<: *default
  host: 127.0.0.1
  database: erp_system_test

production:
  <<: *default
  database: erp_system_production
