default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: hahaha123
  pool: 5

development:
  <<: *default
  database: erp_system_development

test:
  <<: *default
  database: erp_system_test

production:
  <<: *default
  database: erp_system_production
